name: Automated unit test CI
run-name: ${{ github.actor }} triggered an automated tests workflow
on: [push]

jobs:
  Test_CI:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
        name: Install dependencies
      - run: npm ci
        name: Run tests
      - run: npm test
